In [1]:
import matplotlib.pyplot as plt
import networkx as nx
import pandas as pd

Write the code to find a government type page that has the highest degree centrality among other government type pages. The code should print the facebook page name and its degree centrality measure. 

Use the files (“facebook_page_details.csv” and “facebook_page_edges.csv”) from datasets folder on the blackboard. The “facebook_page_edges.csv” file contains edges information that represent mutual links between various facebook pages. The node IDs represent facebook pages. The details of facebook page ids will be found in “facebook_page_details.csv”file.

In [8]:
fb_details_url = "https://github.com/Nate-Cheney/CIS-405-DataSets/raw/refs/heads/main/facebook_page_details.csv"
fb_details_df = pd.read_csv(fb_details_url)
fb_details_df.head()

   id                                     page_name   page_type
0   0                      The Voice of China 中国好声音      tvshow
1   1                 U.S. Consulate General Mumbai  government
2   2                                          ESET     company
3   3  Consulate General of Switzerland in Montreal  government
4   4             Mark Bailey MP - Labor for Miller  politician

In [7]:
fb_edges_url = "https://github.com/Nate-Cheney/CIS-405-DataSets/raw/refs/heads/main/facebook_page_edges.csv"
fb_edges_df = pd.read_csv(fb_edges_url)
fb_edges_df.head()

   id_1   id_2
0     0  18427
1     1  21708
2     1  22208
3     1  22171
4     1   6829

In [11]:
# Drop non-government rows from the details dataframe
gov_details_df = fb_details_df[fb_details_df["page_type"] == "government"]
gov_details_df.head()

    id                                     page_name   page_type
1    1                 U.S. Consulate General Mumbai  government
3    3  Consulate General of Switzerland in Montreal  government
8    8            T.C. Mezar-ı Şerif Başkonsolosluğu  government
9    9           Army ROTC Fighting Saints Battalion  government
10  10                           NASA Student Launch  government

In [12]:
# Drop non-government rows from the edges dataframe
gov_ids = gov_details_df["id"]
gov_edges_df = fb_edges_df[
    fb_edges_df["id_1"].isin(gov_ids) & 
    fb_edges_df["id_2"].isin(gov_ids)
]
gov_edges_df.head()

   id_1   id_2
1     1  21708
2     1  22208
3     1  22171
4     1   6829
5     1  16590

In [15]:
# Create graph
G = nx.from_pandas_edgelist(gov_edges_df, source="id_1", target="id_2")
print(f"Number of gov pages: {G.number_of_nodes()}.\nNumber of gov connections: {G.number_of_edges()}")

Number of gov pages: 6828.
Number of gov connections: 81367

In [27]:
# Calculate degree centrality
gov_deg_centrality = nx.centrality.degree_centrality(G)

# Get the page with the highest (top) centrality
top_centrality_id, top_centrality_degree = sorted(gov_deg_centrality.items(), key=lambda x:x[1], reverse=True)[0]
top_centrality_name = fb_details_df.loc[fb_details_df["id"] == top_centrality_id, "page_name"].iloc[0]

In [29]:
print(f"The '{top_centrality_name}' page has the highest degree centrality at: {top_centrality_degree}.")

The 'U.S. Army' page has the highest degree centrality at: 0.09799326204775158.